# Numpy

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

What is an array?

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.


In [1]:
!pip install numpy

In [1]:
import numpy as np

### Intro to np

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [8]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

We can access the elements in the array using square brackets. When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

In [12]:
a[0]

1

This section covers 1D array, 2D array, ndarray, vector, matrix

You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

In [14]:
ex=np.array([[1,2,3],[2,3,4]])
ex

array([[1, 2, 3],
       [2, 3, 4]])

Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3.

How to create a basic array

To create a NumPy array, you can use the function **np.array()**

In [15]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [16]:
val=np.array([5,2,3,45,5,66])
val

array([ 5,  2,  3, 45,  5, 66])

In [17]:
a.ndim

1

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [32]:
#read
out=np.array(['nisam',12,343],ndmin=2)
print(out)
out.ndim

[['nisam' '12' '343']]


2

In [34]:
out.size

3

In [35]:
out.shape

(1, 3)

In [37]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [38]:
array_example = np.array([[[0, 1, 2, 3],

                           [4, 5, 6, 7]],


                          [[0, 1, 2, 3],

                           [4, 5, 6, 7]],


                          [[0 ,1 ,2, 3],

                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [39]:
array_example.ndim

3

In [44]:
print(array_example.ndim)
print(array_example.size)
print(array_example.shape)

3
24
(3, 2, 4)


In [41]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [40]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [44]:
np.array([1,1,2],dtype="float")

array([1., 1., 2.])

In [41]:
np.array([1,2,'nisam',0])

array(['1', '2', 'nisam', '0'], dtype='<U11')

In [12]:
np.array([1.,2.,3.0])

array([1., 2., 3.])

In [48]:
##dimensions
np.array([[1,2],[3,4]],ndmin=5)

array([[[[[1, 2],
          [3, 4]]]]])

In [62]:
np.array([[1,5,7,9],[1,2,3,6],[1,2,3,4],[5,6,7,8]])

array([[1, 5, 7, 9],
       [1, 2, 3, 6],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
a=np.array([[[1,2,3],[3,4,5]]])
a.ndim

3

In [75]:
a[0][0][1]

2

In [56]:
#dtype
# np.array([1,2,3],dtype=complex)

In [77]:
##data access
a = np.array([[1,2],[3,4]])### index works
a

array([[1, 2],
       [3, 4]])

In [78]:
a[0][1]

2

In [68]:
a[1][1]

4

In [24]:
a[1][0]

3

In [79]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [87]:
array_example2 = np.array([[[0, 1, 62, 3],

                           [4, 9, 6, 7]],


                          [[0, 1, 11, 33],

                           [4, 5, 6, 7]],


                          [[0 ,1 ,12, 3],

                           [44, 5, 6, 37]]])
array_example2

array([[[ 0,  1, 62,  3],
        [ 4,  9,  6,  7]],

       [[ 0,  1, 11, 33],
        [ 4,  5,  6,  7]],

       [[ 0,  1, 12,  3],
        [44,  5,  6, 37]]])

In [94]:
array_example2[2][0][2]

12

In [95]:
np.array((1,2,3))

array([1, 2, 3])

In [98]:
np.array(((1,2,3),(4,5,6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
# x = np.array([(1,2),(3,4)],dtype = [('c','<i2'),('d','<i8')])
# x

In [34]:
type(x[0][0])

numpy.int32

In [32]:
type(x[0][1])

numpy.int64

In [36]:
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [6]:
##passing different type

In [ ]:
#matrix is subclass of an arraay

In [103]:
##sub class arra
np.matrix([[1,2],[4,3]])

matrix([[1, 2],
        [4, 3]])

In [102]:
np.matrix([1,2,3])

matrix([[1, 2, 3]])

In [104]:
np.mat([1,2,3])

matrix([[1, 2, 3]])

In [107]:
##how to convert array into matrix
sol=np.mat(np.array([[1,2,3],[4,5,6]]))
sol.ndim

2

In [108]:
np.mat('1 2; 3 4; 7 6')

matrix([[1, 2],
        [3, 4],
        [7, 6]])

In [112]:
type(array_example)

numpy.ndarray

In [109]:
a = [1,2]
a

[1, 2]

In [ ]:
issubclass(np.nd)

In [114]:
issubclass(np.ndarray,np.matrix)

False

In [115]:
issubclass(np.matrix,np.ndarray)

True

## np.asarray

In [118]:
type(a)

list

In [119]:
np.asarray(a)

array([1, 2])

In [120]:
b = np.array([1,2,3,4,5])
np.asarray(b)

array([1, 2, 3, 4, 5])

In [121]:
a = np.array([1.,2],dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [123]:
np.asarray(a)

array([1., 2.], dtype=float32)

### np.asanyarray

In [124]:
a = np.matrix([[1,2]])
np.asanyarray(a)

matrix([[1, 2]])

In [125]:
a = [1,2,3,4,5,55,66]
np.asanyarray(a)

array([ 1,  2,  3,  4,  5, 55, 66])

In [126]:
b  =np.matrix([[1,2,3,4],[4,45,54,4543]])
np.asanyarray(b)

matrix([[   1,    2,    3,    4],
        [   4,   45,   54, 4543]])

In [7]:
##deep and shallow copy


In [57]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [58]:
y=x

In [59]:
y

array([1, 2, 3])

In [62]:
y[0] = 23423
y

array([23423,     2,     3])

In [63]:
x

array([23423,     2,     3])

In [65]:
z = np.copy(x)
z

array([23423,     2,     3])

In [68]:
z[1] = 365
z

array([23423,   365,     3])

In [69]:
x

array([23423,     2,     3])

In [70]:
y

array([23423,     2,     3])

In [127]:
norm_list =[['B8', 'B9', 'B10', 'B11'],
['C8', 'C9', 'C10', 'C11'],
['D8', 'D9', 'D10', 'D11']]

In [143]:
val = np.array([['B8', 'B9', 'B10', 'B11'],
['C8', 'C9', 'C10', 'C11'],
['D8', 'D9', 'D10', 'D11']])

In [147]:
val[1][2]

'C10'

In [136]:
val_mat = np.matrix(val)
val_mat

matrix([['B8', 'B9', 'B10', 'B11'],
        ['C8', 'C9', 'C10', 'C11'],
        ['D8', 'D9', 'D10', 'D11']], dtype='<U3')

In [152]:
b=np.array([[1,2,3],[4,5,6]])
b[1][1]

5

In [155]:
c=np.mat([[1,2,3],[4,5,6]])
c[1,1]


5

In [149]:
val_mat[1,2]

'C10'

In [131]:
np.asanyarray(val_mat)

matrix([['B8', 'B9', 'B10', 'B11'],
        ['C8', 'C9', 'C10', 'C11'],
        ['D8', 'D9', 'D10', 'D11']], dtype='<U3')

In [132]:
np.asanyarray(norm_list)

array([['B8', 'B9', 'B10', 'B11'],
       ['C8', 'C9', 'C10', 'C11'],
       ['D8', 'D9', 'D10', 'D11']], dtype='<U3')

In [81]:
val

array([['B8', 'B9', 'B10', 'B11'],
       ['C8', 'C9', 'C10', 'C11'],
       ['D8', 'D9', 'D10', 'D11']], dtype='<U3')

In [82]:
val[0][1]

'B9'

In [83]:
val[2][-1]

'D11'

### np.fromfunction

In [98]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [102]:
np.fromfunction(lambda i,j,z,m:i*j*z*m,(3,3,3,3))

array([[[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  1.,  2.],
         [ 0.,  2.,  4.]],

        [[ 0.,  0.,  0.],
         [ 0.,  2.,  4.],
         [ 0.,  4.,  8.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  2.,  4.],
         [ 0.,  4.,  8.]],

        [[ 0.,  0.,  0.],
         [ 0.,  4.,  8.],
         [ 0.,  8., 16.]]]])

In [85]:
#create a new i dm array from an iterable object

### np.fromiter

In [107]:
iterable =( x*x for x in range(5))
type(iterable)

generator

In [106]:
type(np.fromiter(iterable,float))

numpy.ndarray

In [110]:
a = (range(10))
a

range(0, 10)

In [113]:
np.fromiter(a,float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### np.fromstring

In [162]:
b = np.fromstring('235 355 34 4 34 43 433 434 3 343',sep=' ',dtype=int)
b

array([235, 355,  34,   4,  34,  43, 433, 434,   3, 343])

In [159]:
np.fromstring('1,2',dtype=int,sep=',')

array([1, 2])

In [120]:
np.array(['a','b','12'])

array(['a', 'b', '12'], dtype='<U2')

In [ ]:

##create array from other arrays

In [163]:
x1 = np.array([1,2,3,4])
x2 = np.array(['a','b','12','34'])
x3 = np.array([1.1,2,3,4])
x4 = np.array([1.1,2,3,4])

In [164]:
type(x3)

numpy.ndarray

In [128]:
f = np.core.records.fromarrays([x1,x2,x3,x4])
f

rec.array([(1, 'a', 1.1, 1.1), (2, 'b', 2. , 2. ), (3, '12', 3. , 3. ),
           (4, '34', 4. , 4. )],
          dtype=[('f0', '<i4'), ('f1', '<U2'), ('f2', '<f8'), ('f3', '<f8')])

In [134]:
f[3][-1]

4.0

## data types

In [165]:
my_list = [1,2,3]
arr = np.array(my_list)
print('array value: ',arr)
print('Type of array: ',type(arr))
print('Dimension of matrix: ',arr.ndim)
print('Size of the array: ',arr.size)
print('Shape of array: ',arr.shape)
print('Data type of array',arr.dtype)


array value:  [1 2 3]
Type of array:  <class 'numpy.ndarray'>
Dimension of matrix:  1
Size of the array:  3
Shape of array:  (3,)
Data type of array int32


In [143]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_list)
print('array value: ',mat)
print('Type of array: ',type(arr))
print('Dimension of matrix: ',arr.ndim)
print('Size of the array: ',arr.size)
print('Shape of array: ',arr.shape)
print('Data type of array',arr.dtype)

array value:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type of array:  <class 'numpy.ndarray'>
Dimension of matrix:  2
Size of the array:  9
Shape of array:  (3, 3)
Data type of array int32


### arange

In [172]:
list(range(10.5,20.5))

TypeError: 'float' object cannot be interpreted as an integer

In [181]:
np.arange(10.5,20.5,2.6)#try binjus problem here

array([10.5, 13.1, 15.7, 18.3])

In [179]:
from numpy import arange,asarray,asanyarray,matrix,array

In [180]:
arange(12,1,-2.3)

array([12. ,  9.7,  7.4,  5.1,  2.8])

In [178]:
b  = np.arange(20,10,-2.5)
b

array([20. , 17.5, 15. , 12.5])

In [3]:
num=np.arange(1,11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### linspace

In [188]:
np.linspace(1,10,7,endpoint=False,dtype='int64')

array([1, 2, 3, 4, 6, 7, 8], dtype=int64)

In [28]:
np.linspace(1,10,5,endpoint=False)

array([1. , 2.8, 4.6, 6.4, 8.2])

In [15]:
##tril

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [192]:
np.zeros((4,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [165]:
np.zeros((5,6,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [193]:
np.ones((10,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [195]:
12+np.ones((3,5))

array([[13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.]])

In [196]:
mat = np.eye(7)
mat

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### More Functions

## logspace

In [145]:
np.logspace(2.0,3.0,num=30,base=2)

array([4.        , 4.09675824, 4.19585702, 4.29735296, 4.40130404,
       4.50776964, 4.61681061, 4.72848923, 4.8428693 , 4.96001618,
       5.07999679, 5.20287968, 5.32873505, 5.45763481, 5.5896526 ,
       5.72486383, 5.86334577, 6.00517753, 6.15044013, 6.29921658,
       6.45159185, 6.60765302, 6.76748924, 6.93119183, 7.09885432,
       7.27057248, 7.44644443, 7.62657065, 7.81105404, 8.        ])

In [46]:
np.arange().shape

(16,)

In [59]:
x  =np.arange(16).reshape((-243,8))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

## diag

In [64]:
x  =np.arange(16).reshape((-243,8))

In [65]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [67]:
y  = np.array([[1,2],[4,3]])
y

array([[1, 2],
       [4, 3]])

In [69]:
np.diag(y)

array([1, 3])

## diagflat

In [80]:
np.diagflat([[1]],k=5)

array([[0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### tri

In [93]:
np.tri(16,12,1,dtype=int)

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [99]:
np.tri(4,6,k=-1)

array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

### tril

In [101]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
np.tril([[1,2,3,4],[4,5,6,6],[7,8,9,8]],k=1)

array([[1, 2, 0, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 8]])

### triu

In [112]:
np.triu([[1,2,3],[4,5,6],[7,8,9]],k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

## Random Number

### rand

In [116]:
np.random.rand(2,8)

array([[0.7796908 , 0.94355446, 0.16997025, 0.58468673, 0.51388268,
        0.22412708, 0.37069235, 0.52484352],
       [0.94753489, 0.64866644, 0.9454608 , 0.24393105, 0.03548428,
        0.82365264, 0.98329071, 0.95664287]])

## randn

In [118]:
np.random.randn(8,3)

array([[ 0.28387341,  0.19214323, -0.05400912],
       [-0.50284178, -0.27770071, -0.49635921],
       [ 0.74572971,  0.3592211 , -1.1681768 ],
       [-0.45315988, -0.11478516,  1.2338971 ],
       [-0.83403617,  1.99655867, -0.65300445],
       [ 1.05856078, -0.17222881, -1.64922522],
       [ 0.34278008,  1.40484182, -1.24390447],
       [ 1.22109814, -0.94117238,  0.79890367]])

### randint

In [128]:
np.random.randint(1,10,(5,5))

array([[1, 5, 1, 3, 7],
       [4, 7, 1, 4, 9],
       [2, 1, 8, 3, 6],
       [9, 6, 2, 1, 9],
       [2, 2, 8, 9, 1]])

In [2]:
from numpy.random import randint as ri

In [132]:
a = ri(1,100,30)
a.shape

(30,)

In [135]:
b = a.reshape(2,3,5)
b

array([[[43,  2, 19, 65, 20],
        [87, 97, 39, 91, 40],
        [ 8, 78, 92, 30, 95]],

       [[84, 30, 17, 42, 30],
        [44,  7, 40, 15, 19],
        [27, 64, 44, 26, 83]]])

In [143]:
c = a.reshape(15,-43543)
c

array([[43,  2],
       [19, 65],
       [20, 87],
       [97, 39],
       [91, 40],
       [ 8, 78],
       [92, 30],
       [95, 84],
       [30, 17],
       [42, 30],
       [44,  7],
       [40, 15],
       [19, 27],
       [64, 44],
       [26, 83]])

In [144]:
print(a.shape)
print(b.shape)
print(c.shape)

(30,)
(2, 3, 5)
(15, 2)


In [4]:
ri(1,100,(4,4))

array([[56, 60, 20, 42],
       [82, 61, 77,  5],
       [10,  9, 75, 57],
       [28,  6, 66, 59]])

### sorting

In [5]:
m = ri(1,100,10)
print(m)
print(np.sort(m))

[19 60 14 27  6 85 66  3 35 60]
[ 3  6 14 19 27 35 60 60 66 85]


In [9]:
m = ri(1,100,25).reshape(5,5)
print(m)
print(np.sort(m,axis=0))

[[25 57  2 88 19]
 [53 88 35 78 34]
 [56 55 65 84 29]
 [33 42 82 49 17]
 [75 37  1 34  8]]
[[25 37  1 34  8]
 [33 42  2 49 17]
 [53 55 35 78 19]
 [56 57 65 84 29]
 [75 88 82 88 34]]


In [12]:
m

array([[25, 57,  2, 88, 19],
       [53, 88, 35, 78, 34],
       [56, 55, 65, 84, 29],
       [33, 42, 82, 49, 17],
       [75, 37,  1, 34,  8]])

In [13]:
print(m.max())
print(m.min())

88
1


## argmax

In [14]:
print(m.argmax())

3


In [16]:
m.argmax(axis=0)

array([4, 1, 3, 0, 1], dtype=int64)

## indexing and slicing

In [17]:
m

array([[25, 57,  2, 88, 19],
       [53, 88, 35, 78, 34],
       [56, 55, 65, 84, 29],
       [33, 42, 82, 49, 17],
       [75, 37,  1, 34,  8]])

In [18]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [29]:
arr[[2,4,9]]

array([2, 4, 9])

In [32]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print(mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

[[29 79 20 79 20]
 [34 33 34 77 78]
 [86 36 47 39 16]]


array([[79, 79],
       [33, 77],
       [36, 39]])

In [33]:
mat

array([[29, 79, 20, 79, 20],
       [34, 33, 34, 77, 78],
       [86, 36, 47, 39, 16]])

In [40]:
mat[:,3]

array([79, 77, 39])

In [41]:
mat[1:3,3:5]

array([[77, 78],
       [39, 16]])

In [42]:
#subsetting with condition
mat = np.array(ri(10,100,15)).reshape(3,5)
mat>50

array([[False,  True,  True, False,  True],
       [False,  True, False, False,  True],
       [False, False, False, False, False]])

In [45]:
mat[mat>=50]

array([71, 79, 92, 57, 68])

In [47]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(mat)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [48]:
mat_slice = mat[:2,:2]
print('sliced matrix...\n',mat_slice)

sliced matrix...
 [[11 12]
 [21 22]]


In [50]:
mat_slice[0,0] = 1000
mat_slice

array([[1000,   12],
       [  21,   22]])

## FUNCTIONS are NOT ENDING 

In [51]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print('mat1....\n',mat1)
print('mat1....\n',mat2)

mat1....
 [[5 5 8]
 [7 3 3]
 [4 4 7]]
mat1....
 [[8 8 5]
 [9 7 1]
 [9 8 9]]


In [52]:
mat1*mat2

array([[40, 40, 40],
       [63, 21,  3],
       [36, 32, 63]])

In [54]:
mat1@mat2

array([[157, 139, 102],
       [110, 101,  65],
       [131, 116,  87]])

In [56]:
mat1/0

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [57]:
mat1

array([[5, 5, 8],
       [7, 3, 3],
       [4, 4, 7]])

In [58]:
mat1+100

array([[105, 105, 108],
       [107, 103, 103],
       [104, 104, 107]])

In [62]:
mat1**2

array([[25, 25, 64],
       [49,  9,  9],
       [16, 16, 49]], dtype=int32)

In [61]:
pow(mat1,3)

array([[125, 125, 512],
       [343,  27,  27],
       [ 64,  64, 343]], dtype=int32)

## broadcasting

In [63]:
start = np.zeros((4,4))
start = start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [64]:
add_rows = np.array([1,0,2,5])
print(add_rows)

[1 0 2 5]


In [66]:
y = start+add_rows
y

array([[101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.]])

In [67]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [68]:
y =start+add_cols
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [8]:
##element and row wise operation

In [71]:
mat1

array([[5, 5, 8],
       [7, 3, 3],
       [4, 4, 7]])

In [72]:
mat2

array([[8, 8, 5],
       [9, 7, 1],
       [9, 8, 9]])

In [75]:
np.exp(mat1)

array([[ 148.4131591 ,  148.4131591 , 2980.95798704],
       [1096.63315843,   20.08553692,   20.08553692],
       [  54.59815003,   54.59815003, 1096.63315843]])

In [76]:
np.log10(mat1)

array([[0.69897   , 0.69897   , 0.90308999],
       [0.84509804, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.84509804]])

In [74]:
np.sqrt(mat1)

array([[2.23606798, 2.23606798, 2.82842712],
       [2.64575131, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.64575131]])

## more